trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  PYTHON_VERSION: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -c "import sys; import os; print('Python', sys.version); assert os.path.exists('frontend/app.py') and os.path.exists('backend/main.py')"
  displayName: 'Sanity check'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '.'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish artifacts' 